name: Performance Budget Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4
      
    
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build

        # 4) Instalar Lighthouse CI (CLI)
      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.13.x

      # 5) Rodar LHCI contra build local
      #    Serve a pasta de build (ajuste "dist" se usar outra saída)
      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx lhci autorun \
            --upload.target=filesystem \
            --collect.staticDistDir=dist \
            --collect.numberOfRuns=2 \
            --assert.assertions."categories:performance".minScore=0.85

      # 6) Upload dos relatórios como artifact
      #    Use um nome simples, sem espaços/caracteres especiais.
      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ".lighthouseci/*"
          if-no-files-found: error
          
        
      - name: Check bundle size
        run: |
          # Get build sizes
          JS_SIZE=$(find dist/assets -name "*.js" -exec du -cb {} + | grep total | cut -f1)
          CSS_SIZE=$(find dist/assets -name "*.css" -exec du -cb {} + | grep total | cut -f1 2>/dev/null || echo "0")
          
          # Convert to KB
          JS_SIZE_KB=$((JS_SIZE / 1024))
          CSS_SIZE_KB=$((CSS_SIZE / 1024))
          
          echo "JavaScript bundle size: ${JS_SIZE_KB}KB"
          echo "CSS bundle size: ${CSS_SIZE_KB}KB"
          
          # Performance budgets (in KB)
          JS_BUDGET=10000
          CSS_BUDGET=5000
          
          # Check budgets
          if [ $JS_SIZE_KB -gt $JS_BUDGET ]; then
            echo "❌ JavaScript bundle size (${JS_SIZE_KB}KB) exceeds budget (${JS_BUDGET}KB)"
            exit 1
          else
            echo "✅ JavaScript bundle size within budget"
          fi
          
          if [ $CSS_SIZE_KB -gt $CSS_BUDGET ]; then
            echo "❌ CSS bundle size (${CSS_SIZE_KB}KB) exceeds budget (${CSS_BUDGET}KB)"
            exit 1
          else
            echo "✅ CSS bundle size within budget"
          fi
          
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
