name: Performance Budget Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build
        run: npm run build

      - name: Check bundle size
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -d dist/assets ]; then
            echo "ℹ️ Pasta dist/assets não existe; definindo tamanhos como 0."
            JS_SIZE=0; CSS_SIZE=0
          else
            export LC_ALL=C
            JS_SIZE=$(find dist/assets -type f -name "*.js" -exec du -cb {} + 2>/dev/null | grep -E "\btotal$" | cut -f1 || echo "0")
            JS_SIZE=${JS_SIZE:-0}
            CSS_SIZE=$(find dist/assets -type f -name "*.css" -exec du -cb {} + 2>/dev/null | grep -E "\btotal$" | cut -f1 || echo "0")
            CSS_SIZE=${CSS_SIZE:-0}
          fi
          JS_SIZE_KB=$(( JS_SIZE / 1024 ))
          CSS_SIZE_KB=$(( CSS_SIZE / 1024 ))
          echo "JavaScript bundle size: ${JS_SIZE_KB}KB"
          echo "CSS bundle size: ${CSS_SIZE_KB}KB"
          JS_BUDGET=10000
          CSS_BUDGET=5000
          if [ "${JS_SIZE_KB}" -gt "${JS_BUDGET}" ]; then
            echo "❌ JavaScript bundle size (${JS_SIZE_KB}KB) exceeds budget (${JS_BUDGET}KB)"; exit 1; fi
          if [ "${CSS_SIZE_KB}" -gt "${CSS_BUDGET}" ]; then
            echo "❌ CSS bundle size (${CSS_SIZE_KB}KB) exceeds budget (${CSS_BUDGET}KB)"; exit 1; fi
          echo "✅ Bundles dentro do budget"

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
